### ISSUE TITLE
Verify that ETag headers are generated

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/static-ldp#12]
And also verify that `If-Match`, `If-Modified-Since`, etc. headers are handled properly.

**Comment by DiegoPino** [comment]
For NonRDFSources, would [sha1_file](http://php.net/sha1_file) be fine for you? It does not require to put all into memory so more efficient than applying the checksum algorithm to the `file_get_contents`.
I'm using it (and caching it then later) and seems to perform pretty nice. If yes, can do a pull request tomorrow with header handling also, basically the same utility class I have on my local repo of https://github.com/esmero/esmero-ldp.

**Comment by acoburn** [comment]
@DiegoPino that is _exactly_ the sort of thing I'm thinking about. It would be great to have a PR from you!

**Comment by acoburn** [comment]
@DiegoPino thinking through this some more, I think that we should use the file MTime and the size to generate the etag for a resource. That will be _way_ faster than computing a full checksum.

**Comment by DiegoPino** [comment]
@acoburn will refactor that pull in the next few days. This Week has sadly other priorities so if others want to do it before, we can close this one. 
So based on size means weak eTag then? Same goes for Containers?

**Comment by acoburn** [comment]
@DiegoPino using size and mtime for static resources means strong etags. (It's just way more efficient than reading an entire file through a hash function). For containers, I'll have to see whether the serialization method is deterministic or not; if it is deterministic, strong ETags can be used there, too (again, based on mtime).

**Comment by DiegoPino** [comment]
@acoburn Ok, both combined makes them almost unique, at least in the context of that single resource (don't bother about the edge cases). Will refactor then and  handle  If-Match, If-Modified-Since to reject invalid(not matching) or respond correctly if not modified.

**Comment by acoburn** [comment]
@DiegoPino thanks! and if you don't mind, I'll take some of the code you wrote in #14 and apply that now (mostly to resolve #2)

**Comment by acoburn** [comment]
@DiegoPino I'm leaving this issue for you, if you still want to take it.

**Comment by DiegoPino** [comment]
@acoburn no worries, i got it. Will pull tonight after you all have merged (just avoiding rebases)

**Comment by acoburn** [comment]
Thanks @DiegoPino! You should be all set now.

**Comment by DiegoPino** [comment]
@acoburn i'm refactoring a bit more after directory, file and html were moved to other methods, whole mechanic got a bit too deeply tied to the generation itself, and i needed to move all this part on top to avoid building the whole response just to have it discarded.
Luckily i just finished! But something is not working completely and i'm missing that 304, will give it a look again tomorrow morning, probably just a stupid late night comparison mistype. Also, Symfony uses `If-Non-Match` instead so will have to duplicate some existing code inside the response object to match this issue if we are using positive conditionals instead of negative ones.

**Comment by acoburn** [comment]
@DiegoPino refactor away! I was feeling that the methods were getting to be too complicated, so that is great. I don't know if it means more smaller methods or even separating some of that out into its own class, but whatever you do will be tremendously helpful. I'll hold off on making any changes until you land this so that you don't have to rebase over any conflicts.

**Comment by acoburn** [comment]
Resolved via https://github.com/trellis-ldp/static-ldp/commit/738e82a2936a0d6018ce95fd330df441adff25a7
