### ISSUE TITLE
Incorrect static field

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/static-ldp#19]
On [this line](https://github.com/trellis-ldp/static-ldp/blob/master/src/Controller/ResourceController.php#L188) there is a use of `DateTime::W3c` -- it should be `DateTime::W3C`.

**Comment by acoburn** [comment]
I'm holding off on this until #12 (and any associated refactoring) is complete.

**Comment by DiegoPino** [comment]
@acoburn solved via https://github.com/trellis-ldp/static-ldp/pull/22/
