### ISSUE TITLE
Setting the true Accept

### ISSUE THREAD

**Issue by whikloj** [trellis-ldp/static-ldp#21]
We have a couple locations where we could get an array or a string from a `$request->headers->get()` that we should account for like [here](https://github.com/trellis-ldp/static-ldp/blob/master/src/Controller/ResourceController.php#L86)

But also, we should probably use the response from [getResponseFormat](https://github.com/trellis-ldp/static-ldp/blob/master/src/Controller/ResourceController.php#L131) or some similar function to set the **true** response type. As that allows us to determine that the most correct representation that we support is being returned.

For instance if you have 
`Accept: application/ld+json, text/html; q=0.5`

[This line](https://github.com/trellis-ldp/static-ldp/blob/master/src/Controller/ResourceController.php#L86) would make us return HTML even though json-ld is preferred. (I think, haven't tested)

Perhaps we should set some `protected` or `private` class variable with the selected mimeType and EasyRdf format that we can check through out the request?

**Comment by acoburn** [comment]
@whikloj you are completely correct w/r/t to the Accept handling. The current code is a bit of a kludge, and it should be cleaned up.

**Comment by whikloj** [comment]
Resolved with 738e82a2936a0d6018ce95fd330df441adff25a7
