### ISSUE TITLE
Create a simple RDF description of NonRDFSources

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/static-ldp#26]
This would involve "describes" and "describedBy" links on the various resources. Use hashURIs as per trellis or make use of an existing file on the filesystem (e.g. `foo.jpg.ttl` is used to describe `foo.jpg`)

**Comment by ajs6f** [comment]
https://tools.ietf.org/html/rfc6892

**Comment by ajs6f** [comment]
Possible design: special name for a directory (`package` or something). A directory with that name doesn't become a Basic Container. Instead, it is expected to contain binary and one or more RDF files. All RDF files are considered to be descriptions of the binary.

**Comment by whikloj** [comment]
Ok, so when we hit a directory named `package` then instead of displaying `package` we grab a representation from inside the package based on Content-type <=> extension mapping again? Then display a configurable predicate (`dc:title` or whatever) as the title of the package?

**Comment by acoburn** [comment]
If we go this route, we'd definitely want to make the name of that "special directory" configurable.

**Comment by ajs6f** [comment]
That would be my idea, but I'm just throwing that out there. Maybe it's better not even to have a `dc:title` thing but just use the filename. KIS-KIS (Keep It Simple - Keep It Static).

**Comment by ajs6f** [comment]
Or you double up the nesting so you can have more than one file of description, but maybe not.
