### ISSUE TITLE
Migrate Silex to new Symfony component

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/static-ldp#38]
Silex is now deprecated in favor of the new Symfony components.

**Comment by DiegoPino** [comment]
Article on moving to Symfony 4 comp: 
https://medium.com/@peter.lafferty/converting-a-silex-project-to-a-symfony-project-1dc3dc30f049

**Comment by acoburn** [comment]
Thanks @DiegoPino! that article will be super helpful.

**Comment by DiegoPino** [comment]
Hu! This one.. https://github.com/rectorphp/rector not sure if 100% accurate (i did not even know such tools existed..)  but could speed the most tedious pieces?
